mode: "record"  
# "record": enable camera obs, enable data recording 
# "policy": enable camera obs, disable data recording, run policy 

xarm_api: "192.168.1.243" # replace with your follower's IP
server_xarm_api: "192.168.1.222" # replace with your leader's IP
robot_urdf_path: "./assets/xarm7/xarm7_leap_right.urdf"
zmq_addr: "tcp://192.168.1.123:5557" 
# replace with your server ip. if local machine, use "tcp://127.0.0.1:5557", else use your server ip
record_frequency: 10

use_keyboard_arm_tele: False 
use_kin_arm_tele: True
use_mixed_tele: False
keyboard_tele_speed_scale: [30, 30, 30, 30, 5, 5]   # [+x, -x, +y, -y, +z, -z]

# camera settings
W_resize: 256
H_resize: 192

W: 640
H: 480

camera_to_port: {
  "I" : "3-8",
  "T" : "3-4:1.0",
  "M" : "3-7",
  "R" : "3-3",
}
camera_left_right_order: {
  "I" : ["I-root", "I-tip"],
  "T" : ["T-tip", "T-root"],
  "M" : ["M-tip", "M-root"],
  "R" : ["R-tip", "R-root"],
}
camera_names: ["I-root", "I-tip", "T-root", "T-tip", "M-root", "M-tip", "R-root", "R-tip"]
rs_camera_names: ["d435"]
aux_rs_camera_names: []

default_camera_opts : {
  "input_format": "mjpeg",
  "video_size": "1280x480", 
  "framerate": "25",        
}
rs_fps: 30  # 15 or 30

# policy mode 
eval_ckpt_path: null
eval_ckpt_config_path: null

Detector:
  families: "tag25h9"
  quad_decimate:  1.0
  quad_sigma: 0.0
  tag_size: 0.002  # meters

april_tag_config:
  I:
    big_eye: "I-tip"
    cam_k:
      - [346.20127473104355,   0.0,                  323.4809660401248]
      - [0.0,                  345.42818537369453,   222.23996581194163]
      - [0.0,                  0.0,                  1.0]
    dist: [-0.0794039469163624,0.06301500445090094,-0.005239454261123167,0.000906811549243316,-0.03785402836059528]
  M:
    big_eye: "M-tip"
    cam_k:
      - [351.91661375,   0.        , 334.65980427]
      - [  0.        , 350.3316893 , 229.33303518]
      - [  0.        ,   0.        ,   1         ]
    dist: [-0.10122013,  0.07903637,  0.00424957,  0.00345012, -0.04635722]
  R:
    big_eye: "R-tip"
    cam_k:
        - [520.5878142639937, 0.0, 326.07191960575557]
        - [0.0, 520.9457742431183, 216.6933080291371]
        - [0.0, 0.0, 1.0]
  T:
    big_eye: "T-tip"
    cam_k:
      - [341.94997148,   0.        , 336.45662577]
      - [  0.        , 342.48713908, 220.40036818]
      - [  0.        ,   0.        ,   1.        ]
    dist: [-0.14676256,  0.13712995, -0.00644845,  0.00743834, -0.08850039]
  center_tag_id: 0
  transfer_to_center:
    tag_id:
      0:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0], [0], [0]]
      1:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.0045], [-0.004], [0]]
      2:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.0045], [-0.004], [0]]
      3:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.0045], [0.004], [0]]
      4:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.0045], [0.004], [0]]
      24:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0], [-0.0085], [0]]
      9:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0], [0.0085], [0]]
      25:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00263], [-0.0085], [0]]
      8:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00263], [0.0085], [0]]
      10:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00263], [0.0085], [0]]
      23:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00263], [-0.0085], [0]]
      26:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00526], [-0.0085], [0]]
      7:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00526], [0.0085], [0]]
      11:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00526], [0.0085], [0]]
      22:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00526], [-0.0085], [0]]
      27:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00789], [-0.0085], [0]]
      6:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.00789], [0.0085], [0]]
      12:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00789], [0.0085], [0]]
      21:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.00789], [-0.0085], [0]]
      28:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [-0.0085], [0]]
      5:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [0.0085], [0]]
      13:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [0.0085], [0]]
      20:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [-0.0085], [0]]
      29:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [-0.00607], [0]]
      34:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [0.00607], [0]]
      14:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [0.00607], [0]]
      19:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [-0.00607], [0]]
      30:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [-0.00364], [0]]
      33:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [0.00364], [0]]
      15:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [0.00364], [0]]
      18:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [-0.00364], [0]]
      31:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [-0.001215], [0]]
      32:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[0.01051], [0.001215], [0]]
      16:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [0.001215], [0]]
      17:
        r: [[1, 0, 0],[0, 1, 0],[0, 0, 1]]
        p: [[-0.01051], [-0.001215], [0]]

